// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nazymgzhnjfpxjdsscml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5henltZ3pobmpmcHhqZHNzY21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyOTUxNzcsImV4cCI6MjA0OTg3MTE3N30.Bg1yCafQ7iythCQ8MiSMU2cfxchlaYn1_epKZauhulw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);